name: '发送邮件通知'
description: '发送 CI/CD 邮件通知'

inputs:
  status:
    description: 'Job 状态 (success/failure)'
    required: true
  type:
    description: '通知类型 (ci/release)'
    required: false
    default: 'ci'
  version:
    description: '版本号（发布时使用）'
    required: false
    default: ''
  mail_username:
    description: 'SMTP 用户名'
    required: true
  mail_password:
    description: 'SMTP 密码'
    required: true
  mail_to:
    description: '收件人'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 获取东八区时间
      id: time
      shell: bash
      run: echo "cst=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

    - name: 发送邮件
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ inputs.mail_username }}
        password: ${{ inputs.mail_password }}
        subject: "${{ inputs.status == 'success' && '✅' || '❌' }} [${{ github.repository_owner }}/${{ github.event.repository.name }}] ${{ inputs.type == 'release' && '发布' || '代码检查' }}${{ inputs.version && format(' {0}', inputs.version) || '' }} #${{ github.run_number }}"
        to: ${{ inputs.mail_to }}
        from: ${{ inputs.mail_username }}
        html_body: |
          <!DOCTYPE html>
          <html>
          <head><meta charset="utf-8"></head>
          <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background-color: #f6f8fa; padding: 20px;">
            <div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">
              <div style="background: ${{ inputs.status == 'success' && 'linear-gradient(135deg, #10b981, #059669)' || 'linear-gradient(135deg, #ef4444, #dc2626)' }}; padding: 24px; text-align: center;">
                <h1 style="color: white; margin: 0; font-size: 24px;">
                  ${{ inputs.type == 'release' && '发布' || '代码检查' }}${{ inputs.version && format(' {0}', inputs.version) || '' }}
                </h1>
                <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0 0; font-size: 14px;">
                  ${{ github.repository }}
                </p>
              </div>
              <div style="padding: 24px;">
                <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
                  <tr>
                    <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; color: #6b7280; width: 100px;">时间</td>
                    <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; font-weight: 500;">
                      <span style="color: #374151;">${{ steps.time.outputs.cst }} (UTC+8)</span>
                    </td>
                  </tr>
                  <tr>
                    <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; color: #6b7280;">事件</td>
                    <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; font-weight: 500;">
                      <span style="background: #e5e7eb; padding: 4px 8px; border-radius: 4px; font-size: 12px;">${{ github.event_name }}</span>
                    </td>
                  </tr>
                  <tr>
                    <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; color: #6b7280;">分支</td>
                    <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; font-weight: 500;">${{ github.ref_name }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; color: #6b7280;">提交</td>
                    <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb;">
                      <code style="background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 12px;">${{ github.sha }}</code>
                    </td>
                  </tr>
                  <tr>
                    <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; color: #6b7280;">提交者</td>
                    <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb;">
                      <img src="https://github.com/${{ github.actor }}.png?size=80" style="width: 40px; height: 40px; border-radius: 50%; vertical-align: middle; margin-right: 10px;">
                      <a href="https://github.com/${{ github.actor }}" style="color: #2563eb; text-decoration: none; font-weight: 600;">${{ github.actor }}</a>
                      <span style="color: #6b7280; font-size: 12px; margin-left: 8px;">${{ github.event.head_commit.author.email || github.event.pusher.email || '' }}</span>
                    </td>
                  </tr>
                  <tr>
                    <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; color: #6b7280;">提交信息</td>
                    <td style="padding: 12px 0; border-bottom: 1px solid #e5e7eb; color: #374151;">${{ github.event.head_commit.message || github.event.pull_request.title || '-' }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 12px 0; color: #6b7280;">状态</td>
                    <td style="padding: 12px 0;">
                      <span style="display: inline-block; background: ${{ inputs.status == 'success' && '#dcfce7' || '#fee2e2' }}; color: ${{ inputs.status == 'success' && '#166534' || '#991b1b' }}; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600;">
                        ${{ inputs.status == 'success' && '✅ 成功' || '❌ 失败' }}
                      </span>
                    </td>
                  </tr>
                </table>
              </div>
              <div style="padding: 16px 24px; background: #f9fafb; text-align: center;">
                <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" style="display: inline-block; background: #2563eb; color: white; padding: 10px 24px; border-radius: 6px; text-decoration: none; font-weight: 500;">查看详情</a>
              </div>
            </div>
          </body>
          </html>
